# Generated by Django 5.0.1 on 2024-02-10 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Age should be positive')])),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits long.', regex='^\\d{10}$')])),
                ('monthly_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Salary should be positive')])),
                ('approved_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Salary should be positive')])),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Loan Amount should be positive')])),
                ('tenure', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Tenure should be positive')])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Interst Rate should be positive')])),
                ('monthly_payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Monthly paymemt should be positive')])),
                ('emi_paid_on_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='No of Emi should be positive')])),
                ('date_of_approval', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
